import cliMeta from './cli-meta.json';

/** Latest Prysm release documented by this site. Regenerated by tools/gen-cli-reference.sh. */
export const PRYSM_VERSION: string = cliMeta.version;

export const LINKS = {
	github: 'https://github.com/OffchainLabs/prysm',
	releases: 'https://github.com/OffchainLabs/prysm/releases',
	discord: 'https://discord.gg/qEZK94mFXP',
	docsRepo: 'https://github.com/OffchainLabs/prysm-documentation',
};
